pipeline {
    agent any


    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            when {
                changeset '**/vote/*'
            }
            steps {
                echo 'Compiling voting app'
                dir('vote') {
                    sh 'pip install -r requirements.txt' 
                }
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }            
            when {
                changeset '**/vote/*'
            }
            
            steps {
                echo 'Testing voting app'
                dir('vote') {
                    sh 'pip install -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }

        stage('Package-container') {
            agent any

            when {
                changeset '**/vote/*'
		changeRequest target: 'master'
            }
            
            steps {
                echo 'Building Vote container'
                script {
                    docker.withRegistry("https://registry.hub.docker.com/v1/","dockerhub_token") {
                        def image = docker.build("galusjir/vote:${env.BUILD_ID}", "vote")
                        image.push()
                    }
                }
                
            }
        }
        
    }
}
