pipeline {
    
    agent {
        docker {
          image   'maven:3.6.1-jdk-8-alpine'
          args    '-v $HOME/.m2:/root/.m2'
        }
    }

    stages {
        stage('Build') {
            when {
                changeset '**/worker/*'
            }
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile' 
                }
            }
        }
        stage('Test') {
            when {
                changeset '**/worker/*'
            }
            steps {
                echo 'Testing the worker'
                dir('worker') {
                    sh 'mvn clean test' 
                }
            }
        }
        
        stage('PAckage') {
            when {
                changeset '**/worker/*'
            }
            steps {
                echo 'Packaging the project'
                dir('worker') {
                    sh 'mvn package -DSkipTests' 
                }
            }
        }
        
    }
}