pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image   'maven:3.6.1-jdk-8-alpine'
                    args    '-v $HOME/.m2:/root/.m2'
                }
            }
            when {
                changeset '**/worker/*'
            }
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile' 
                }
            }
        }
        stage('Test') {
            agent {
                docker {
                    image   'maven:3.6.1-jdk-8-alpine'
                    args    '-v $HOME/.m2:/root/.m2'
                }
            }
            when {
                changeset '**/worker/*'
            }
            steps {
                echo 'Testing the worker'
                dir('worker') {
                    sh 'mvn clean test' 
                }
            }
        }
        
        stage('PAckage') {
            agent {
                docker {
                    image   'maven:3.6.1-jdk-8-alpine'
                    args    '-v $HOME/.m2:/root/.m2'
                }
            }
            
            when {
                changeset '**/worker/*'
            }
            steps {
                echo 'Packaging the project'
                dir('worker') {
                    sh 'mvn package -DSkipTests' 
                }
            }
        }

        stage('Docker-Package') {
            agent any
            when {
              changeset '**/worker/*'
              changeRequest target: 'master'
            }
            steps {
                script {
                    docker.withRegistry("https://registry.hub.docker.com/v1/","dockerhub_token") {
                        def image = docker.build("galusjir/worker:${env.BUILD_ID}", "worker")
                        image.push()
                    }
                }
                
            }
        }
        
    }
}
